[build]
publish = "docs-dist"
command = "npm install --legacy-peer-deps && npm run docs:build"

[build.environment]
NODE_VERSION = "18"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[context.production.environment]
NODE_ENV = "production"

[context.deploy-preview.environment]
NODE_ENV = "development"

# Headers for security and performance
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
for = "*.js"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "*.css"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "*.html"
[headers.values]
Cache-Control = "public, max-age=3600"
