name: 🚀 功能请求
description: 建议一个新功能或改进
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        感谢您的功能建议！我们很乐意听到您的想法。

  - type: textarea
    id: problem
    attributes:
      label: "问题描述"
      description: 您遇到了什么问题？这个功能将解决什么问题？
      placeholder: |
        描述您当前遇到的问题或限制...
        例如：我在使用 useLocalStorage 时，希望能够...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: "建议的解决方案"
      description: 您希望我们如何解决这个问题？
      placeholder: |
        详细描述您建议的功能或改进...
        例如：添加一个新的 hook useSessionStorage，它应该...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: "使用场景"
      description: 这个功能在什么情况下会被使用？
      placeholder: |
        描述具体的使用场景...
        例如：
        1. 当用户需要临时存储数据时...
        2. 在处理表单状态时...
    validations:
      required: true

  - type: textarea
    id: api-design
    attributes:
      label: "API 设计建议"
      description: 如果您有具体的 API 设计想法，请分享
      render: typescript
      placeholder: |
        // 建议的 API 接口
        interface UseNewHookOptions {
          // 选项参数
        }

        interface UseNewHookReturn {
          // 返回值
        }

        function useNewHook(options?: UseNewHookOptions): UseNewHookReturn {
          // 使用示例
        }

  - type: textarea
    id: alternatives
    attributes:
      label: "替代方案"
      description: 您考虑过哪些替代解决方案？
      placeholder: |
        描述您尝试过的其他方法或现有的替代方案...

  - type: dropdown
    id: priority
    attributes:
      label: "优先级"
      description: 这个功能对您有多重要？
      options:
        - "低 - 有更好但不是必需的"
        - "中 - 会显著改善开发体验"
        - "高 - 对我的项目很重要"
        - "紧急 - 阻碍了我的开发进度"
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: "预估复杂度"
      description: 您认为实现这个功能的复杂程度如何？
      options:
        - "简单 - 小改动或配置"
        - "中等 - 需要一些开发工作"
        - "复杂 - 重大功能或架构变更"
        - "不确定"
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: "示例代码"
      description: 如果可能，提供一些使用示例
      render: tsx
      placeholder: |
        import { useNewHook } from '@ai-code/hooks';

        function MyComponent() {
          const { data, loading } = useNewHook({
            // 配置选项
          });

          return (
            <div>
              {loading ? '加载中...' : data}
            </div>
          );
        }

  - type: textarea
    id: references
    attributes:
      label: "参考资料"
      description: 有相关的文档、库或文章可以参考吗？
      placeholder: |
        - [相关文档链接]
        - [类似功能的库]
        - [技术文章]

  - type: checkboxes
    id: contribution
    attributes:
      label: "贡献意愿"
      description: 您是否愿意帮助实现这个功能？
      options:
        - label: 我愿意提交 Pull Request 来实现这个功能
        - label: 我可以帮助测试这个功能
        - label: 我可以帮助编写文档
        - label: 我可以提供使用反馈

  - type: checkboxes
    id: checklist
    attributes:
      label: "检查清单"
      description: 在提交之前，请确认：
      options:
        - label: 我已经搜索了现有的 issues，确认这不是重复请求
          required: true
        - label: 我已经阅读了项目文档
          required: true
        - label: 这个功能符合项目的目标和范围
          required: true
        - label: 我提供了足够详细的描述和用例
          required: true 